### ISSUE TITLE
binary files cause lineup to raise an exception

### ISSUE THREAD

**Issue by chrismo** [mysterysci/rubocop_lineup#16]
if there are any binary files in the repo that have been changed, it can't read these properly because the proper `rb` mode isn't set.

```
invalid byte sequence in UTF-8
/Users/chrismo/.rbenv/versions/2.5.6/lib/ruby/gems/2.5.0/gems/git-1.5.0/lib/git/diff.rb:135:in `split'
/Users/chrismo/.rbenv/versions/2.5.6/lib/ruby/gems/2.5.0/gems/git-1.5.0/lib/git/diff.rb:135:in `process_full_diff'
/Users/chrismo/.rbenv/versions/2.5.6/lib/ruby/gems/2.5.0/gems/git-1.5.0/lib/git/diff.rb:109:in `process_full'
/Users/chrismo/.rbenv/versions/2.5.6/lib/ruby/gems/2.5.0/gems/git-1.5.0/lib/git/diff.rb:68:in `each'
/Users/chrismo/.rbenv/versions/2.5.6/lib/ruby/gems/2.5.0/gems/rubocop_lineup-0.5.0/lib/rubocop_lineup/diff_liner.rb:41:in `map'
/Users/chrismo/.rbenv/versions/2.5.6/lib/ruby/gems/2.5.0/gems/rubocop_lineup-0.5.0/lib/rubocop_lineup/diff_liner.rb:41:in `process'
/Users/chrismo/.rbenv/versions/2.5.6/lib/ruby/gems/2.5.0/gems/rubocop_lineup-0.5.0/lib/rubocop_lineup/diff_liner.rb:27:in `initialize'
/Users/chrismo/.rbenv/versions/2.5.6/lib/ruby/gems/2.5.0/gems/rubocop_lineup-0.5.0/lib/rubocop_lineup/diff_liner.rb:9:in `new'
/Users/chrismo/.rbenv/versions/2.5.6/lib/ruby/gems/2.5.0/gems/rubocop_lineup-0.5.0/lib/rubocop_lineup/diff_liner.rb:9:in `diff_uncommitted'
/Users/chrismo/.rbenv/versions/2.5.6/lib/ruby/gems/2.5.0/gems/rubocop_lineup-0.5.0/lib/rubocop_lineup.rb:18:in `block in line_em_up'
/Users/chrismo/.rbenv/versions/2.5.6/lib/ruby/gems/2.5.0/gems/rubocop_lineup-0.5.0/lib/rubocop_lineup.rb:17:in `chdir'
/Users/chrismo/.rbenv/versions/2.5.6/lib/ruby/gems/2.5.0/gems/rubocop_lineup-0.5.0/lib/rubocop_lineup.rb:17:in `line_em_up'
/Users/chrismo/.rbenv/versions/2.5.6/lib/ruby/gems/2.5.0/gems/rubocop_lineup-0.5.0/lib/rubocop_lineup/duck_punch_rubocop.rb:39:in `find'
/Users/chrismo/.rbenv/versions/2.5.6/lib/ruby/gems/2.5.0/gems/rubocop-0.78.0/lib/rubocop/runner.rb:64:in `find_target_files'
/Users/chrismo/.rbenv/versions/2.5.6/lib/ruby/gems/2.5.0/gems/rubocop-0.78.0/lib/rubocop/runner.rb:34:in `run'
/Users/chrismo/.rbenv/versions/2.5.6/lib/ruby/gems/2.5.0/gems/rubocop-0.78.0/lib/rubocop/cli/command/execute_runner.rb:21:in `execute_runner'
/Users/chrismo/.rbenv/versions/2.5.6/lib/ruby/gems/2.5.0/gems/rubocop-0.78.0/lib/rubocop/cli/command/execute_runner.rb:13:in `run'
/Users/chrismo/.rbenv/versions/2.5.6/lib/ruby/gems/2.5.0/gems/rubocop-0.78.0/lib/rubocop/cli/command.rb:10:in `run'
/Users/chrismo/.rbenv/versions/2.5.6/lib/ruby/gems/2.5.0/gems/rubocop-0.78.0/lib/rubocop/cli/environment.rb:17:in `run'
/Users/chrismo/.rbenv/versions/2.5.6/lib/ruby/gems/2.5.0/gems/rubocop-0.78.0/lib/rubocop/cli.rb:65:in `run_command'
/Users/chrismo/.rbenv/versions/2.5.6/lib/ruby/gems/2.5.0/gems/rubocop-0.78.0/lib/rubocop/cli.rb:72:in `execute_runners'
/Users/chrismo/.rbenv/versions/2.5.6/lib/ruby/gems/2.5.0/gems/rubocop-0.78.0/lib/rubocop/cli.rb:41:in `run'
/Users/chrismo/.rbenv/versions/2.5.6/lib/ruby/gems/2.5.0/gems/rubocop-0.78.0/exe/rubocop:13:in `block in <top (required)>'
```

**Comment by chrismo** [comment]
Well, mode/shmode, it should just skip these files :)
